### ISSUE TITLE
unhandled exception when connection timeout

### ISSUE THREAD

**Issue by benny856694** [chenasraf/ctelnet_dart#1]
LateError (LateInitializationError: Field '_socket@20410799' has not been initialized.)

**Comment by chenasraf** [comment]
Thanks for the report @benny856694! I will get on fixing it immediately.

**Comment by chenasraf** [comment]
@benny856694 Please try [v0.1.6](https://pub.dev/packages/ctelnet/versions/0.1.6) and let me know how it works for you. Notice some types may have changed a bit.

**Comment by benny856694** [comment]
Tested working, thanks for your effort, will report if any further bugs

**Comment by benny856694** [comment]
BTW, stay safe in Israel, it's a tough time for Israel.

**Comment by chenasraf** [comment]
Glad it works. And thank you! 🙏🏼🙏🏼❤️

**Comment by chenasraf** [comment]
@benny856694 It's not closed I think, maybe my link in the profile is wrong - here it is: https://x.com/casraf_dev or better yet on mastodon https://fosstodon.org/@casraf

How can I help you?

**Comment by chenasraf** [comment]
Replied on X
On mastodon you can reply privately
